# Generated by Django 5.2.7 on 2025-11-13 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_rating_user_avatar_user_username_paymentcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата рождения (можно указать только один раз)', null=True),
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Номер карты лояльности', max_length=16, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Баланс бонусов', max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Общая сумма покупок', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_birthday_bonus', models.DateField(blank=True, help_text='Дата последнего начисления бонусов на день рождения', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
