# Generated by Django 5.2.7 on 2025-11-20 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_default_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Вопрос пользователя', max_length=500)),
                ('answer', models.TextField(help_text='Ответ на вопрос')),
                ('category', models.CharField(choices=[('delivery', 'Доставка'), ('return', 'Возврат'), ('payment', 'Оплата'), ('order', 'Заказ'), ('loyalty', 'Программа лояльности'), ('other', 'Другое')], default='other', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('order', 'question'),
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя пользователя', max_length=255)),
                ('email', models.EmailField(help_text='Email для ответа', max_length=254)),
                ('message', models.TextField(help_text='Текст сообщения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Ответ администратора', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь (если авторизован)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение поддержки',
                'verbose_name_plural': 'Сообщения поддержки',
                'ordering': ('-created_at',),
            },
        ),
    ]
