# Generated by Django 5.2.7 on 2025-11-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faq_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Прикрепленное изображение', null=True, upload_to='support_messages/'),
        ),
    ]
