# Generated by Django 5.2.7 on 2025-11-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_supportmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='image',
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Прикрепленный файл (фото, документ и т.д.)', null=True, upload_to='support_messages/'),
        ),
    ]
