# Generated by Django 5.2.7 on 2025-11-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_supportmessage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text='Биография автора', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Место рождения', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, help_text='Дата смерти', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_place',
            field=models.CharField(blank=True, help_text='Место смерти', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фото автора', null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='author',
            name='short_bio',
            field=models.TextField(blank=True, help_text='Краткая биография (для карточек)', null=True),
        ),
    ]
