# Generated by Django 5.2.7 on 2025-11-20 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_author_options_author_biography_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], help_text='Тип действия', max_length=10)),
                ('model_name', models.CharField(help_text='Название модели', max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID объекта')),
                ('object_repr', models.CharField(help_text='Строковое представление объекта', max_length=255)),
                ('changed_fields', models.JSONField(default=dict, help_text="Измененные поля: {'field': {'old': '...', 'new': '...'}}")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время изменения')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, который внес изменение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='core_auditl_created_1a76fa_idx'), models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx')],
            },
        ),
    ]
