# Generated by Django 5.2.7 on 2025-11-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auditlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_created_1a76fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_user_id_2ff9b7_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='changed_fields',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], default='create', help_text='Тип действия', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Изменения (поле: {old: значение, new: значение})'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP адрес', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User Agent', null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx'),
        ),
    ]
