# Generated by Django 5.2.7 on 2025-11-20 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_auditlog_core_auditl_created_1a76fa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, help_text='Описание действия', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='url_path',
            field=models.CharField(blank=True, help_text='URL страницы', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('download', 'Скачивание'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('register', 'Регистрация'), ('password_reset', 'Сброс пароля'), ('config', 'Изменение конфигурации'), ('export', 'Экспорт данных'), ('import', 'Импорт данных'), ('other', 'Прочее')], default='other', help_text='Тип действия', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Время действия'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, help_text='Название модели (если применимо)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID объекта (если применимо)', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, help_text='Строковое представление объекта', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который выполнил действие (null для неавторизованных)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
