# Generated by Django 5.2.7 on 2025-11-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_wishlist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_book',
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_stationery',
        ),
        migrations.AddField(
            model_name='stationery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stationery/'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'book'), ('user', 'stationery')},
        ),
    ]
